org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.20
forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=infohud
mod_name=InfoHUD
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.crazerium.infohud
mod_authors=EvgenWarGold, Crazerium
mod_description=A configurable information HUD for Minecraft Forge 1.20.1.